spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shockdb
    username: root
    password: atybrclbvf
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
server:
  port: 8888